/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package lanchonetelistas;
import lanchonetelistas.Pedido;
/**
 *
 * @author anani
 */


public class escolha_pedido extends javax.swing.JFrame {
    private String itemSelecionado;
    private double valorSelecionado;
    private interfacegrafica telaPrincipal;
    private interfacegrafica main;
    

public escolha_pedido(interfacegrafica main) {
    this.main = main;
    initComponents();
}





   

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(escolha_pedido.class.getName());
    
    /**
     * Creates new form escolha_pedido
     */
    public escolha_pedido() {
        initComponents();
    

    }
    

   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        add_1 = new javax.swing.JButton();
        add_2 = new javax.swing.JButton();
        add_3 = new javax.swing.JButton();
        add_4 = new javax.swing.JButton();
        add_5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pedido_escolhido = new javax.swing.JLabel();
        feito_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Cardápio");

        jLabel2.setText("Cachorro Quente - 5,50R$");

        jLabel3.setText("X-Burger - 10,90R$");

        jLabel4.setText("Guaraná - 4,50R$");

        jLabel5.setText("Batata-Frita - 7,50R$");

        jLabel6.setText("MilkShake - 11R$");

        add_1.setText("Add");
        add_1.addActionListener(this::add_1ActionPerformed);

        add_2.setText("Add");
        add_2.addActionListener(this::add_2ActionPerformed);

        add_3.setText("Add");

        add_4.setText("Add");

        add_5.setText("Add");

        jLabel7.setText("Pedido Adicionado:");

        feito_btn.setText("FEITO");
        feito_btn.addActionListener(this::feito_btnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(feito_btn)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(add_1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(add_2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(add_5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(add_3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(add_4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(pedido_escolhido, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(feito_btn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(add_1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(add_2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(add_3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(add_4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(add_5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pedido_escolhido, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_1ActionPerformed
                                    
    Pedido p = new Pedido("Cachorro Quente", 1, 5.50);
    pedido_escolhido.setText("Cachorro Quente");

    main.adicionarPedido(p);
    }//GEN-LAST:event_add_1ActionPerformed

    private void add_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_2ActionPerformed
    Pedido p = new Pedido("Cachorro Quente", 1, 5.50);
    pedido_escolhido.setText("Cachorro Quente");

    main.adicionarPedido(p);
    }//GEN-LAST:event_add_2ActionPerformed

    private void feito_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feito_btnActionPerformed
         if (itemSelecionado == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione algum item!");
        return;
    }

    telaPrincipal.adicionarItemNaTabela(itemSelecionado, 1, valorSelecionado);

    this.dispose();
    }//GEN-LAST:event_feito_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new escolha_pedido().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_1;
    private javax.swing.JButton add_2;
    private javax.swing.JButton add_3;
    private javax.swing.JButton add_4;
    private javax.swing.JButton add_5;
    private javax.swing.JButton feito_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel pedido_escolhido;
    // End of variables declaration//GEN-END:variables
}
