/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lanchonetelistas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anani
 */
public class interfacegrafica extends javax.swing.JFrame {
    // Lista normal
// Estruturas de dados
DefaultTableModel modeloTabela;

private java.util.List<Pedido> lista = new java.util.ArrayList<>();
private java.util.Stack<Pedido> pilha = new java.util.Stack<>();
private java.util.Queue<Pedido> fila = new java.util.LinkedList<>();

// Modo de visualização (0 = lista, 1 = pilha, 2 = fila)
private int modoView = 0;




    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfacegrafica.class.getName());

    /**
     * Creates new form interfacegrafica
     */
   
    public interfacegrafica() {
       initComponents(); // sempre primeiro
    modeloTabela = (DefaultTableModel) tabela_itens.getModel();
    atualizarLabelView();
    }
    


    public void adicionarPedido(Pedido p) {
     lista.add(p);
    pilha.push(p);
    fila.add(p);

    atualizarTabela();
}

   

    public void adicionarItemNaTabela(String item, int quantidade, double valor) {
         DefaultTableModel model = (DefaultTableModel) tabela_itens.getModel();
         model.insertRow(0, new Object[]{ item, quantidade, valor });
    }

    public void adicionarAoPedido(Pedido p) {
    DefaultTableModel model = (DefaultTableModel) tabela_itens.getModel();
    model.insertRow(0, new Object[]{
        p.item,
        p.quantidade,
        p.valor
    });
}
private void atualizarTabela() {
    DefaultTableModel model = (DefaultTableModel) tabela_itens.getModel();
    model.setRowCount(0);

    switch (modoView) {
        case 0 -> {
            // LISTA
            for (Pedido p : lista) {
                model.addRow(new Object[]{ p.item, p.quantidade, p.valor });
            }
        }

        case 1 -> {
            // PILHA (topo primeiro)
            for (int i = pilha.size() - 1; i >= 0; i--) {
                Pedido p = pilha.get(i);
                model.addRow(new Object[]{ p.item, p.quantidade, p.valor });
            }
        }

        case 2 -> {
            // FILA
            for (Pedido p : fila) {
                model.addRow(new Object[]{ p.item, p.quantidade, p.valor });
            }
        }
    }
}

private void atualizarLabelView() {
    switch (modoView) {
        case 0 -> lbl_view.setText("Visualização: Lista");
        case 1 -> lbl_view.setText("Visualização: Pilha (LIFO)");
        case 2 -> lbl_view.setText("Visualização: Fila (FIFO)");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_itens = new javax.swing.JTable();
        add_pedidos = new javax.swing.JButton();
        alt_view = new javax.swing.JButton();
        remover_pedido = new javax.swing.JButton();
        lbl_view = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Sistema Lanchonete");

        tabela_itens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item", "Quantidade", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tabela_itens);

        add_pedidos.setText("Add Pedidos");
        add_pedidos.addActionListener(this::add_pedidosActionPerformed);

        alt_view.setText("Alterar Visualização");
        alt_view.addActionListener(this::alt_viewActionPerformed);

        remover_pedido.setText("Remover");
        remover_pedido.addActionListener(this::remover_pedidoActionPerformed);

        lbl_view.setText("Lista");

        jLabel2.setText("View atual:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(add_pedidos)
                        .addGap(60, 60, 60)
                        .addComponent(alt_view)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(remover_pedido)
                        .addGap(15, 15, 15))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lbl_view)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_view)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_pedidos)
                    .addComponent(alt_view)
                    .addComponent(remover_pedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_pedidosActionPerformed
           escolha_pedido tela = new escolha_pedido(this);
    tela.setVisible(true);
    }//GEN-LAST:event_add_pedidosActionPerformed

    private void alt_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt_viewActionPerformed
          modoView = (modoView + 1) % 3;  
    atualizarTabela();
    atualizarLabelView();
    }//GEN-LAST:event_alt_viewActionPerformed

    private void remover_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remover_pedidoActionPerformed
      if (lista.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Não há itens para remover.");
        return;
    }

    Pedido removido = null;

    switch (modoView) {

        case 0 -> {
            int linha = tabela_itens.getSelectedRow();
            if (linha < 0) {
                JOptionPane.showMessageDialog(this, "Selecione um item para remover!");
                return;
            }
            removido = lista.get(linha);
        }

        case 1 -> {
            removido = pilha.pop();
        }

        case 2 -> {
            removido = fila.poll();
        }
    }

    lista.remove(removido);
    pilha.remove(removido);
    fila.remove(removido);

    atualizarTabela();
    }//GEN-LAST:event_remover_pedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfacegrafica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_pedidos;
    private javax.swing.JButton alt_view;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_view;
    private javax.swing.JButton remover_pedido;
    private javax.swing.JTable tabela_itens;
    // End of variables declaration//GEN-END:variables
}
